language: objective-c
xcode_project: ios/src/Conflux for iOS.xcodeproj
xcode_scheme: conflux
script:
- xctool -workspace "ios/src/Conflux for iOS.xcodeproj/project.xcworkspace" -scheme conflux -sdk iphonesimulator -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO 'CODE_SIGN_RESOURCE_RULES_PATH=$(SDKROOT)/ResourceRules.plist'

